<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLess18() {
        // récupérer un querybuilder pour créer une query
        $qb = $this->createQueryBuilder('u');

        $now = new \DateTime();
        $now->sub(new \DateInterval('P18Y'));

        // mettre des conditions dans la query
        $qb->where('u.dateNaissance >= :param1')
            ->setParameter('param1', $now);

        // trié par date naissance
        $qb->orderBy('u.dateNaissance');

        return $qb->getQuery()->getResult();
    }
}
